version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: nest-rest-core-postgres
    ports:
      - 5435:5432
    env_file:
    - docker.env
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - nest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-rest-core-app
    command: bash -c "pnpm run start:dev:docker"
    ports:
      - '8085:3001'
    depends_on:
      - postgres
    env_file:
      - '.env.dev.docker'
    networks:
      - nest

networks:
  nest: 
    driver: bridge
     