version: '3'

services:
  nginx:
    container_name: nest-rest-core-prod-nginx
    build: nginx
    volumes:
      - .:/app
    ports:
      - "8010:80"
      - "8011:5432"
      - "8012:3000"
    depends_on:
      - app
    networks:
      - nest-rest-core-prod

  postgres:
    image: postgres:latest
    container_name: nest-rest-core-prod-postgres
    env_file:
    - docker.env.prod
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - nest-rest-core-prod

  app:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile.prod
    container_name: nest-rest-core-prod-app
    command: bash -c "pnpm run start:prod:docker"
    depends_on:
      - postgres
      - prometheus
    env_file:
      - '.env.docker.prod'
    networks:
      - nest-rest-core-prod

  prometheus:
    image: prom/prometheus
    container_name: nest-rest-core-prod-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - nest-rest-core-prod

  grafana:
    image: grafana/grafana
    container_name: nest-rest-core-prod-grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - nest-rest-core-prod

  loki:
    container_name: nest-rest-core-prod-loki
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml:ro
    restart: always
    networks:
      - nest-rest-core-prod

networks:
  nest-rest-core-prod: 
    driver: bridge
     
volumes:
  grafana-data:
     