version: "3"

services:
  postgres:
    image: postgres:15
    container_name: nest-rest-core-dev-postgres
    ports:
      - 5435:5432
    env_file:
      - .docker.dev.env
    volumes:
      - /data/postgres:/data/postgres

  app:
    build:
      context: ../../
      dockerfile: docker/develop/Dockerfile.dev
    container_name: nest-rest-core-dev-app
    command: bash -c "pnpm run start:dev:docker"
    ports:
      - "3005:3000"
    depends_on:
      - postgres
    env_file:
      - "../../.env.dev"
